### ISSUE TITLE
Design decisions

### ISSUE THREAD

**Issue by morenoh149** [mikolalysenko/foreach-combination#1]
So I take it this implementation is very fast?

looks like you're using a cache. Could you elaborate on how this module achieves very good performance please?

**Comment by mikolalysenko** [comment]
The module generates some code to loop over the array non-recursively.  So, something like:

``` javascript
forEachComb(array, 2, func)
```

becomes:

``` javascript
function forEachComb(array, func) {
  for(var i=0; i<array.length; ++i) {
     for(var j=0; j<i; ++j) {
        func(array[i], array[j])
     }
  }
}
```
